### ISSUE TITLE
Possible issue with Astral Sorcery?

### ISSUE THREAD

**Issue by NihilEntropy** [TheCodex6824/AuraControl#2]
Forge 14.23.5.2854

`java.lang.NullPointerException: Exception in server tick loop
	at hellfirepvp.astralsorcery.common.base.FluidRarityRegistry$ChunkFluidEntryProvider.hasCapability(FluidRarityRegistry.java:343)
	at hellfirepvp.astralsorcery.common.base.FluidRarityRegistry$ChunkFluidEntryProvider.getCapability(FluidRarityRegistry.java:349)
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.getCapability(CapabilityDispatcher.java:108)
	at net.minecraft.world.chunk.Chunk.getCapability(Chunk.java:1571)
	at thecodex6824.auracontrol.AuraWorldGenerator.generate(AuraWorldGenerator.java:42)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)`

Let me know if you need more info.

**Comment by TheCodex6824** [comment]
This is most definitely **not** Astral's fault, I'm not really sure how I missed this in testing. I'll release an update to fix it soon.

**Comment by TheCodex6824** [comment]
The update that fixes this should be [here](https://www.curseforge.com/minecraft/mc-mods/auracontrol/files/3013979), sorry about that!

**Comment by NihilEntropy** [comment]
No problem, thanks for getting on top of that so fast!

**Update:** I'm still getting the issue? There is no difference in the error.

**Comment by NihilEntropy** [comment]
It would seem that astral sorcery is defining a:
`        @Nullable
        @Override
        public <T> T getCapability(@Nonnull Capability<T> capability, @Nullable EnumFacing facing) {
            return hasCapability(capability, facing) ? CAPABILITY_CHUNK_FLUID.cast(defaultImpl) : null;
        }`
at the java:349, and coincidentally at your java:42 it is calling a getCapability... I don't know enough to suggest anything more, but perhaps this is where the issue lies?

**Comment by TheCodex6824** [comment]
Are you sure you're using the latest version (1.0.2)? I just tried it with Astral and everything seemed to work fine.

**Comment by NihilEntropy** [comment]
Sorry! It must have taken a little to update on twitch, its updated now.
